### ISSUE TITLE
Create a secure API to ingest data

### ISSUE THREAD

**Issue by shaneallgeier** [mostateresnet/rimproject#84]
Basically, we will be running a script on each individual computer that gathers a ton of relevant data and sends it off to our server running RIM project which then ingests the data. I also want this API to be secure somehow to prevent random people spamming the API with fake data. Maybe use [HMAC](https://en.wikipedia.org/wiki/HMAC)? If need be, we can separate the "secure" portion of this feature out into its own issue & branch.

Here's an example of what the script generates. It's currently JSON but it can be changed to produce whatever format you prefer:
```
{
  "CPU":"Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz",
  "Displays":[
    {
      "HeightInMillimeters":336,
      "ManufacturerName":"DEL",
      "ProductCodeID":"9405",
      "Resolution":"1920x1080p60",
      "SerialNumberID":"577712016",
      "UserFriendlyName":"OptiPlex 7780",
      "WidthInMillimeters":598
    }
  ],
  "GPUs":[
    {
      "Name":"NVIDIA GeForce GTX 1650"
    },
    {
      "Name":"Intel(R) UHD Graphics 630"
    }
  ],
  "Hostname":"MSU-49G2NF6",
  "Manufacturer":"Dell Inc.",
  "Model":"OptiPlex 7780 AIO",
  "NICs":[
    {
      "MAC":"F35EBAED9BE9",
      "Name":"Intel(R) Wi-Fi 6 AX201 160MHz",
      "Type":"wireless"
    },
    {
      "MAC":"006DA2542003",
      "Name":"Intel(R) Ethernet Connection (11) I219-LM",
      "SwitchName":"HUTC0C-50",
      "SwitchPort":"ge-0/7/27 911-96",
      "Type":"ethernet",
      "VLAN":"62"
    }
  ],
  "RAM":16846733312,
  "Serial":"49G2NF6",
  "Storage":[
    {
      "Model":"BC711 NVMe SK hynix 256GB",
      "Size":256052966400
    }
  ],
  "Users":[
    {
      "IDLE TIME":"none",
      "IS_CURRENT_USER":true,
      "LOGON TIME":"5/15/2022 8:42 PM",
      "SESSIONNAME":"console",
      "STATE":"Active",
      "USERNAME":"abc123"
    }
  ]
}
```

Our database schema will require some changes so we can properly store it all. I think we also should have a way for it to ingest error tracebacks from the script itself if any ever occur - which will also need a spot in the database.

**Comment by shaneallgeier** [comment]
Here's an example of an error traceback:
```
Traceback (most recent call last):
  File "inventory.py", line 303, in main
    'Manufacturer': get_manufacturer(),
  File "inventory.py", line 17, in get_manufacturer
    manufacturer = get_wmic_data('computersystem get manufacturer')
  File "inventory.py", line 272, in get_wmic_data
    results = [xml_to_dict(x) for x in xml_root.findall('./RESULTS/CIM/INSTANCE')]
  File "inventory.py", line 272, in <listcomp>
    results = [xml_to_dict(x) for x in xml_root.findall('./RESULTS/CIM/INSTANCE')]
  File "inventory.py", line 253, in xml_to_dict
    xml_type = xml_types[child.attrib['TYPE']]
KeyError: 'string'```
